name = "threadz"
compatibility_date = "2024-12-01"
pages_build_output_dir = "."

# KV namespace for order storage
# Create it: npx wrangler kv namespace create "ORDERS"
# Then paste the ID below
[[kv_namespaces]]
binding = "ORDERS"
id = "9190f3f184944c9094bbeac430b89422"

[vars]
JWT_SECRET = "threadz-jwt-secret-2024"
BOSTA_API_KEY = "3593a672772ae29d44e4d522c57138dcaf346099c5fc24b998a724ac2592e0bd"
ADMIN_CODE = "CBT2009"
